backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'gallery_business'
    label: 'Gallery Business'
    folder: 'gatsby-project/content/gallery_business'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text', default: "", required: false }
      - label: 'Thumbnail Image'
        name: 'thumbnail_image'
        widget: 'image'
      - { label: 'Video Link', name: 'video_link', widget: 'string', default: "", required: false }
      - { label: 'Web Page Link', name: 'web_page_link', widget: 'string', default: "", required: false }
      - label: "Additional Images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - {label: "Media Section", name: "media_section", widget: "boolean", default: false}
  - name: 'gallery_music'
    label: 'Gallery Music'
    folder: 'gatsby-project/content/gallery_music'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text', default: "", required: false }
      - label: 'Thumbnail Image'
        name: 'thumbnail_image'
        widget: 'image'
      - { label: 'Video Link', name: 'video_link', widget: 'string', default: "", required: false }
      - { label: 'Web Page Link', name: 'web_page_link', widget: 'string', default: "", required: false }
      - label: "Additional Images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - {label: "Media Section", name: "media_section", widget: "boolean", default: false}
  - name: 'gallery_nyu'
    label: 'Gallery NYU'
    folder: 'gatsby-project/content/gallery_nyu'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text', default: "", required: false }
      - label: 'Thumbnail Image'
        name: 'thumbnail_image'
        widget: 'image'
      - { label: 'Video Link', name: 'video_link', widget: 'string', default: "", required: false }
      - { label: 'Web Page Link', name: 'web_page_link', widget: 'string', default: "", required: false }
      - label: "Additional Images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - {label: "Media Section", name: "media_section", widget: "boolean", default: false}
  - name: 'gallery_honors'
    label: 'Gallery Honors'
    folder: 'gatsby-project/content/gallery_honors'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text', default: "", required: false }
      - label: 'Thumbnail Image'
        name: 'thumbnail_image'
        widget: 'image'
      - { label: 'Video Link', name: 'video_link', widget: 'string', default: "", required: false }
      - { label: 'Web Page Link', name: 'web_page_link', widget: 'string', default: "", required: false }
      - label: "Additional Images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - {label: "Media Section", name: "media_section", widget: "boolean", default: false}
  - name: 'gallery_human'
    label: 'Gallery Human Flourishing'
    folder: 'gatsby-project/content/gallery_human'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text', default: "", required: false }
      - label: 'Thumbnail Image'
        name: 'thumbnail_image'
        widget: 'image'
      - { label: 'Video Link', name: 'video_link', widget: 'string', default: "", required: false }
      - { label: 'Web Page Link', name: 'web_page_link', widget: 'string', default: "", required: false }
      - label: "Additional Images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - {label: "Media Section", name: "media_section", widget: "boolean", default: false}
  - name: 'media_section'
    label: 'Media Section'
    folder: 'gatsby-project/content/media-section'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text', default: "", required: false }
      - label: 'Thumbnail Image'
        name: 'thumbnail_image'
        widget: 'image'
      - { label: 'Video Link', name: 'video_link', widget: 'string', default: "", required: false }
      - { label: 'Web Page Link', name: 'web_page_link', widget: 'string', default: "", required: false }
      - label: "Additional Images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
  - name: 'index'
    label: 'Home Page'
    files:
      - name: 'letter'
        label: 'Letter'
        file: 'gatsby-project/content/index/letter/letter.json'
        fields: 
          - { label: 'Teaser', name: 'teaser', widget: 'string' }
          - { label: 'Extended', name: 'extended', widget: 'string' }
          - { label: 'P1 Extended', name: 'p1_extended', widget: 'text' }
          - { label: 'P1', name: 'p1', widget: 'text' }
          - { label: 'P2', name: 'p2', widget: 'text' }
          - { label: 'P3', name: 'p3', widget: 'text' }
          - { label: 'P4', name: 'p4', widget: 'text' }
          - { label: 'P5', name: 'p5', widget: 'text' }
          - { label: 'P6', name: 'p6', widget: 'text' }
          - { label: 'P7', name: 'p7', widget: 'text' }
  - name: 'index_videos'
    label: 'Home Page Videos'
    label_singular: 'Home Page Video'
    folder: 'gatsby-project/content/index/videos'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        date_format: "MM/DD/YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Video Link', name: 'video_link', widget: 'string' }
      - { label: 'Display Image', name: 'image', widget: 'image' }